accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("home")),
    ),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    AccountListView,
    AccountCreateView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,
    ReceiptCreateView,
    ReceiptListView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="expense_category_list",
    ),
    path("accounts/", AccountListView.as_view(), name="account_list"),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
# from unicodedata import name
from django.db import models
from django.conf import settings
from django import forms


USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(("total"), max_digits=10, decimal_places=3)
    tax = models.DecimalField(("tax"), max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        "ExpenseCategory", related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


# Create your views here.
def signup(request):
    if request.method == "GET":
        form = UserCreationForm()
        return render(request, "registration/signup.html", {"form": form})
    else:
        print(request.method)
        print(request.POST)
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password1"]
            password = request.POST["password2"]
            user = User.objects.create_user(
                username=username, password=password
            )
            login(request, user)
            return redirect("home")
        else:
            return render(request, "registration/signup.html", {"form": form})

receipts/views.py
from typing import List
from django.shortcuts import redirect, render
from django.urls import reverse_lazy

from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django import forms

from receipts.models import Account, ExpenseCategory, Receipt

from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipt/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipt/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "expense_category/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "expense_category/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("home")

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create Account</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button">Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h1>Accounts</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>Number of Receipts</th>
                </tr>
            </thead>
            <tbody>
                {% for account in account_list %}
                    <tr>
                        <td>{{ account.name }}</td>
                        <td>{{ account.number }}</td>
                        <td>{{ account.receipts.all|length }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div>
            <h2>
                <a href="{% url 'create_account' %}">Add</a>
            </h2>
        </div>
    </main>
{% endblock content %}

receipts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <nav>
            <ul>
              <li>
                <a href="{% url 'home' %}">Receipts</a>
              </li>
              <li>
                <a href="{% url 'account_list' %}">Accounts</a>
              </li>
              <li>
                <a href="{% url 'expense_category_list' %}">Expenses</a>
              </li>
              {% if user.is_authenticated %}
                <li>
                  <a href="{% url 'logout' %}">Logout</a>
                </li>
              {% else %}
                <li>
                    <a href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li>
                  <a href="{% url 'login' %}">Login</a>
                </li>
              {% endif %}
            </ul>
          </nav>
        {% block content %}
        {% endblock content %} 
    </body>
</html>

receipts/templates/expense_category/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create Category</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button">Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/expense_category/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h1>Expense Categories</h1>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Number of Receipts</th>
                </tr>
            </thead>
            <tbody>
                {% for category in expensecategory_list %}
                    <tr>
                        <td>{{category.name}}</td>
                        <td>{{category.receipts.all|length}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div>
            <h2>
                <a href="{% url 'create_category' %}">Add</a>
            </h2>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipt/create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button">Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

receipts/templates/receipt/list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
                <tr>
                    <th>Vendor</th>
                    <th>Total</th>
                    <th>Tax</th>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Account</th>
                </tr>
            </thead>
            <tbody>
                {% for receipt in receipt_list %}
                    <tr>
                        <td>{{receipt.vendor}}</td>
                        <td>{{receipt.total}}</td>
                        <td>{{receipt.tax}}</td>
                        <td>{{receipt.date|date:"n/j/y"}}</td>
                        <td>{{receipt.category}}</td>
                        <td>{{receipt.account}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div>
            <h2>
                <a href="{% url 'create_receipt' %}">Add</a>
            </h2>
        </div>
    </main>
{% endblock content %}